### ISSUE TITLE
all elements on view becomes nonClickable :(

### ISSUE THREAD

**Issue by dimabiserov** [sudeepag/SAConfettiView#53]
how to fix?

**Comment by KlausFu** [comment]
instead of 
`self.view.addSubview(confettiView)`

you can use 
`self.view.insertSubview(confettiView, belowSubview: clickableView)`

In that case, the `confettiView` ist behind your `clickableView`, so everything in your `clickableView` is clickable

**Comment by dimabiserov** [comment]
thx!
