### ISSUE TITLE
Symbol(s) not found for architecture i386

### ISSUE THREAD

**Issue by jamesallison** [sudeepag/SAConfettiView#8]
Getting this error on iPhone 5 & 4S; non-64 bit devices. Using Cocoapods.

```
Undefined symbols for architecture i386:
  "SAConfettiView.SAConfettiView.__allocating_init (SAConfettiView.SAConfettiView.Type)(frame : __C.CGRect) -> SAConfettiView.SAConfettiView", referenced from:
      AppName.FirstViewController.(functionName (AppName.FirstViewController) -> (Swift.Int, showBigIndicator : Swift.Bool) -> ()).(closure #1).(closure #1) in FirstViewController.o
  "type metadata accessor for SAConfettiView.SAConfettiView", referenced from:
      AppName.FirstViewController.(functionName (AppName.FirstViewController) -> (Swift.Int, showBigIndicator : Swift.Bool) -> ()).(closure #1).(closure #1) in FirstViewController.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by sudeepag** [comment]
1. Are you running on a device or on the simulator?
2. Try cleaning the project and deleting the derived data.
3. Run pod update and build again (ensure that all necessary frameworks are linked).

If that doesn't work, check out [this](http://stackoverflow.com/questions/6984368/undefined-symbols-for-architecture-i386-objc-class-skpsmtpmessage-referenc?page=1&tab=oldest#tab-top) or [this](https://forum.openframeworks.cc/t/fix-for-undefined-symbols-when-building-in-xcode-6/16780).

**Comment by jamesallison** [comment]
Hi Sudeep,

Think I submitted this issue a bit prematurely. Was an issue with Cocopoads, unrelated to SAConfettiView :) Cheers, James
